# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Increased memory (default: 512) to resolve conda envs in jaspy (30/07/2021)
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.disksize.size = '30GB'
  config.vm.box = "rockylinux/9"
  config.vm.synced_folder "C:/vagrant-shares/general", "/vagrant-share", 
      mount_options: ["dmode=755,fmode=644"]
  config.vm.network "private_network", ip: "192.168.50.101"
  config.vm.boot_timeout = 1200
  

config.vm.provision :shell, inline: <<SHELL
set -x
mkdir -p /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh

# Install endpoint RPM to enable access to endpoint repo - for recent git version
yum install -y git wget vim ansible-core

echo "alias vi='vim'" >> ~/.bashrc

echo "[user]" > /home/vagrant/.gitconfig
echo "        name = Ag Stephens" >> /home/vagrant/.gitconfig
echo "        email = ag.stephens@stfc.ac.uk" >> /home/vagrant/.gitconfig
chown vagrant.vagrant /home/vagrant/.gitconfig

cp /home/vagrant/.gitconfig /root/.gitconfig

SHELL

end
