# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Increased memory (default: 512) to resolve conda envs in jaspy (30/07/2021)
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.vm.box = "cedadev/centos7"
  config.vm.box_version = "0.0.1"
  config.vm.synced_folder "C:/vagrant-shares/general", "/vagrant-share", 
      mount_options: ["dmode=755,fmode=644"]
  config.vm.network "private_network", ip: "192.168.50.70"
  
# copy the root key
config.vm.provision :shell, inline: <<SHELL
set -x
mkdir -p /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh

# Install endpoint RPM to enable access to endpoint repo - for recent git version
yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
yum install -y git

yum install -y vim-enhanced
echo "alias vi='vim'" >> ~/.bashrc

echo "[user]" > /home/vagrant/.gitconfig
echo "        name = Ag Stephens" >> /home/vagrant/.gitconfig
echo "        email = ag.stephens@stfc.ac.uk" >> /home/vagrant/.gitconfig
chown vagrant.vagrant /home/vagrant/.gitconfig

cp /home/vagrant/.gitconfig /root/.gitconfig
SHELL

end
