# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Increased memory (default: 512) to resolve conda envs in jaspy (30/07/2021)
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", 3]
  end

  config.vm.box = "cedadev/centos7"
  config.vm.box_version = "0.0.1"
  config.vm.synced_folder "C:/vagrant-shares/general", "/vagrant-share", 
      mount_options: ["dmode=755,fmode=644"]
  config.vm.network "private_network", ip: "192.168.50.99"
  config.vm.boot_timeout = 1200
  
# copy the root key
config.vm.provision :shell, inline: <<SHELL
set -x
mkdir -p /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh

# Install endpoint RPM to enable access to endpoint repo - for recent git version
yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
yum install -y git wget

yum install -y vim-enhanced
echo "alias vi='vim'" >> ~/.bashrc

echo "[user]" > /home/vagrant/.gitconfig
echo "        name = Ag Stephens" >> /home/vagrant/.gitconfig
echo "        email = ag.stephens@stfc.ac.uk" >> /home/vagrant/.gitconfig
chown vagrant.vagrant /home/vagrant/.gitconfig

cp /home/vagrant/.gitconfig /root/.gitconfig

# Install latest miniconda - if needed
if [ ! -d /miniconda ]; then
  base_url=https://repo.anaconda.com/miniconda
  mc_file_name=`curl $base_url/ | grep Linux-x86_64.sh | cut -d'"' -f2 | grep Miniconda3-py39 | sort -t . -k 2 -g | tail -1`
  mc_url=$base_url/$mc_file_name

  cd /
  mc_file=/miniconda.sh

  echo "Downloading: $mc_url"
  wget -O $mc_file $mc_url
  bash $mc_file -b -p /miniconda
fi

# Update .bashrc files to see conda
echo "export PATH=/miniconda/bin:$PATH" >> /root/.bashrc
echo "export PATH=/miniconda/bin:$PATH" >> /home/vagrant/.bashrc

conda init bash
sudo -u vagrant /miniconda/bin/conda init bash

/miniconda/bin/pip install ansible

SHELL

end
