# -*- mode: ruby -*-
# vi: set ft=ruby :

ROOT_IP = "192.168.50.10"
BOX = "generic/rocky9"

# Set the variables for the different nodes in the cluster
wps_ip = ROOT_IP + "4"
mng_ip = ROOT_IP + "5"
bat_ip = ROOT_IP + "6"
dir_ip = ROOT_IP + "7"


# Provision the servers in the order above
Vagrant.configure("2") do |config|
    # Shared configuration for all VMs
    config.vm.box = BOX

    config.vm.define "wps1" do |vb|
        vb.vm.network "private_network", ip: wps_ip
        vb.vm.hostname = "wps1"
        # copy SSH key to root SSH directory
		vb.vm.provision :shell, inline: <<SHELL
			set -x
			mkdir -p /root/.ssh
			cp ~vagrant/.ssh/authorized_keys /root/.ssh
SHELL
    end

    config.vm.define "mngr1" do |vb|
        vb.vm.network "private_network", ip: mng_ip
        vb.vm.hostname = "mngr1"
        # copy SSH key to root SSH directory
		vb.vm.provision :shell, inline: <<SHELL
			set -x
			mkdir -p /root/.ssh
			cp ~vagrant/.ssh/authorized_keys /root/.ssh
SHELL
    end

    config.vm.define "batch1" do |vb|
        vb.vm.network "private_network", ip: bat_ip
        vb.vm.hostname = "batch1"
        # copy SSH key to root SSH directory
		vb.vm.provision :shell, inline: <<SHELL
			set -x
			mkdir -p /root/.ssh
			cp ~vagrant/.ssh/authorized_keys /root/.ssh
SHELL
    end

    config.vm.define "direct1" do |vb|
        vb.vm.network "private_network", ip: dir_ip
        vb.vm.hostname = "direct1"
        # copy SSH key to root SSH directory
		vb.vm.provision :shell, inline: <<SHELL
			set -x
			mkdir -p /root/.ssh
			cp ~vagrant/.ssh/authorized_keys /root/.ssh
SHELL
    end

end
