# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cedadev/centos7"
  config.vm.synced_folder "C:/vagrant-shares/general", "/vagrant-share", 
  config.vm.hostname = "catalogue"
  config.vm.network "private_network", ip: "192.168.50.12"
  
# copy the root key
config.vm.provision :shell, inline: <<SHELL
set -x
mkdir -p /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh

# Install endpoint RPM to enable access to endpoint repo - for recent git version
yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
yum install -y git wget

yum install -y vim-enhanced
echo "alias vi='vim'" >> ~/.bashrc

echo "[user]" > /home/vagrant/.gitconfig
echo "        name = Ag Stephens" >> /home/vagrant/.gitconfig
echo "        email = ag.stephens@stfc.ac.uk" >> /home/vagrant/.gitconfig
chown vagrant.vagrant /home/vagrant/.gitconfig

cp /home/vagrant/.gitconfig /root/.gitconfig
SHELL

end
